### ISSUE TITLE
MySQL Debezium snapshot is interrupted by maxWait

### ISSUE THREAD

**Issue by alexnikitchuk** [kestra-io/plugin-debezium#38]
### Expected Behavior

MySQL Debezium snapshot is completed successfully

### Actual Behaviour

During the initial run, Debezium does table data and database schema [snapshot](https://debezium.io/documentation/reference/stable/connectors/mysql.html#mysql-snapshots). 
With the default `maxWait` time which is 10 seconds, the plugin does not wait until it completes the snapshot and interrupts it.
The same issue occurs if a user sets `maxRecords` which is less than the row count in the captured tables.
To provide data consistency with the source database the plugin should wait until the snapshot is done. 

```
2023-07-12 23:11:06,494 INFO  stra-change-event-source-coordinator d.c.m.MySqlSnapshotChangeEventSource Reading structure of database 'dynamodb-clone'
2023-07-12 23:11:13,126 INFO  WorkerThread io.debezium.embedded.EmbeddedEngine Stopping the embedded engine
2023-07-12 23:11:13,127 INFO  WorkerThread io.debezium.embedded.EmbeddedEngine Waiting for PT5M for connector to stop
2023-07-12 23:11:13,610 INFO  Capture_0    io.debezium.embedded.EmbeddedEngine Stopping the task and engine
2023-07-12 23:11:13,611 INFO  Capture_0    i.d.connector.common.BaseSourceTask Stopping down connector
2023-07-12 23:12:09,054 INFO  stra-change-event-source-coordinator .RelationalSnapshotChangeEventSource Snapshot step 6 - Persisting schema history
2023-07-12 23:12:09,180 WARN  stra-change-event-source-coordinator .s.AbstractSnapshotChangeEventSource Snapshot was interrupted before completion
2023-07-12 23:12:09,180 INFO  stra-change-event-source-coordinator .s.AbstractSnapshotChangeEventSource Snapshot - Final stage
2023-07-12 23:12:09,180 WARN  stra-change-event-source-coordinator i.d.p.ChangeEventSourceCoordinator Change event source executor was interrupted
java.lang.InterruptedException: Interrupted while processing event SchemaChangeEvent [database=, schema=null, ddl=SET character_set_server=utf8mb4, collation_server=utf8mb4_0900_ai_ci, tables=[], type=DATABASE]
	at io.debezium.connector.mysql.MySqlSnapshotChangeEventSource.createSchemaChangeEventsForTables(MySqlSnapshotChangeEventSource.java:532)
	at io.debezium.relational.RelationalSnapshotChangeEventSource.doExecute(RelationalSnapshotChangeEventSource.java:121)
	at io.debezium.pipeline.source.AbstractSnapshotChangeEventSource.execute(AbstractSnapshotChangeEventSource.java:76)
	at io.debezium.pipeline.ChangeEventSourceCoordinator.doSnapshot(ChangeEventSourceCoordinator.java:155)
	at io.debezium.pipeline.ChangeEventSourceCoordinator.executeChangeEventSources(ChangeEventSourceCoordinator.java:137)
	at io.debezium.pipeline.ChangeEventSourceCoordinator.lambda$start$0(ChangeEventSourceCoordinator.java:109)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
2023-07-12 23:12:09,313 INFO  pool-15-thread-1 io.debezium.jdbc.JdbcConnection Connection gracefully closed
2023-07-12 23:12:09,314 INFO  Capture_0    o.a.k.c.s.FileOffsetBackingStore Stopped FileOffsetBackingStore
2023-07-12 23:12:09,314 INFO  Capture_0    f.t.4.12AIsOBFwmo07iIlg1WqQz Debezium ended successfully with 'Connector 'io.debezium.connector.mysql.MySqlConnector' completed normally.'
2023-07-12 23:12:09,319 INFO  WorkerThread f.t.4.12AIsOBFwmo07iIlg1WqQz Ended after receiving 0 records: {}
```

### Steps To Reproduce

1. Run Kestra
2. setup flow to sync from MySQL database with a) hundreds of tables or b) one table with a lot of rows
3. trigger execution

### Environment Information

- Kestra Version: 0.10.0
- Operating System (OS / Docker / Kubernetes): MacOS 13.4 /Docker
- Java Version (If not docker): N/A

### Example flow

id: test-pipeline
namespace: dev
tasks:
  - id: "capture"
    type: "io.kestra.plugin.debezium.mysql.Capture"
    snapshotMode: INITIAL
    properties:
      snapshot.locking.mode: none
    hostname: db.host.com
    port: "3306"
    username: user
    password: pass
    maxRecords: 10
    deleted: ADD_FIELD
    deletedFieldName: "is_deleted"
    metadata: ADD_FIELD
    metadataFieldName: "metadata"
    key: ADD_FIELD
    ignoreDdl: true
    format: WRAP

**Comment by loicmathieu** [comment]
Some background information can be found here: https://github.com/kestra-io/kestra/issues/1728#issuecomment-1634845184

**Comment by loicmathieu** [comment]
We need to use a custom snapshotter to be able to know when the snapshots ends and when the "normal" consumption starts, see https://debezium.io/documentation/reference/stable/connectors/postgresql.html#connector-custom-snapshot

As we cannot wait forever for a snapshot, we will introduce a 'maxSnapshotWait' duration after which the task will fail.
